Updated Register UI
SPO-Career-Portal/SPC-Frontend pull request #11
Opened 2021-06-12 22:00 UTC by navneet-28

![Screenshot 2021-06-13 032743](https://user-images.githubusercontent.com/78998610/121789901-93163980-cbf7-11eb-83c9-1885202199cf.png)
![Screenshot 2021-06-13 032823](https://user-images.githubusercontent.com/78998610/121789903-97daed80-cbf7-11eb-8157-1c54fb0878c9.png)
![Screenshot 2021-06-13 032853](https://user-images.githubusercontent.com/78998610/121789904-9ad5de00-cbf7-11eb-88d0-19e422a1612e.png)

closes #1

2021-06-13 14:17 UTC, kartikcode commented
Remove the welcome text in the template UI. I don't think so we need it. Instead we can have some instructions out there. Also, remove the footer as of now, apart from the copyright claims.

2021-06-13 17:33 UTC, mridul911 requested changes

2021-06-13 17:33 UTC, mridul911 commented on src/views/examples/Register.js
> +                </div>
Also Can you please show validations error just below given field. It is taking too much space and doesn't looks good. Same for password one.

2021-06-13 17:33 UTC, mridul911 commented on src/views/examples/Register.js
> +                        onClick={setEmailError==="valid email"? (e)=> onRegister(e) : undefined}
Use this condition inside onRegister functions. Just use this onClick={(e)=> onRegister(e)} and check conditions at start of function and if false return from that function. Or you can have some disable button for this as well.

2021-06-13 17:33 UTC, mridul911 commented on src/views/examples/Register.js
> +      history.push("../../../");
Please use dispatch here and ignore using such type of navigation. If user is successfully saved it automatically redirect to Admin page no need for some routing here. You can refer how login part is done.

2021-06-14 07:48 UTC, navneet-28 commented
Made all the requested changes.
![Screenshot 2021-06-14 130500](https://user-images.githubusercontent.com/78998610/121857195-fba60900-cd12-11eb-8817-833e0a8d369e.png)

2021-06-14 15:03 UTC, mridul911 approved these changes

2021-06-14 15:04 UTC, merged