Register UI
SPO-Career-Portal/SPC-Frontend pull request #8
Opened 2021-06-07 15:46 UTC by uditpd3000

![Screenshot (5)](https://user-images.githubusercontent.com/75174340/121049658-89469d80-c7d5-11eb-8dfe-97b5f9df0645.png)
![Screenshot (6)](https://user-images.githubusercontent.com/75174340/121049731-98c5e680-c7d5-11eb-96d7-534dd65dbd66.png)

2021-06-07 19:22 UTC, mridul911 requested changes
In general once user submit form please use something similar to login actions so that we can save user using redux-session and Redirect user to dashboard.
You can look into login pull request as well how he hangle email validator and copy that here as well.

2021-06-07 19:22 UTC, mridul911 commented on src/views/examples/Register.js
> +}
1. Don't define a function like this. Be it inside functional component like const functionname = () => {}.
2. Disable Register button till all fields are filled without failing any validation.
3. Kindly check the password in other ways as well like if some user make changes in password after confirm password then also it is giving same error.

2021-06-07 19:22 UTC, mridul911 commented on src/views/examples/Register.js
> +                         }}>{emailError}
Invalid is not looking good please change its position to next line or between email and password.

2021-06-07 19:22 UTC, mridul911 commented on src/views/examples/Register.js
> +}
kindly gave values in console output as of now.

2021-06-12 22:05 UTC, navneet-28 commented
A new PR ( #11 ), with all the requested changes, has been made.

2021-06-14 15:04 UTC, closed without merging